name: lugeasy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  flutter_riverpod: ^2.3.1
  riverpod_annotation: any
  flutter_screenutil: ^5.7.0
  build_runner: ^2.4.11
  cupertino_icons: ^1.0.8
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  sign_in_with_apple: ^5.0.0

flutter:
  uses-material-design: true